### PR TITLE
Changed logo color

### PR DESCRIPTION
**Pull request by ZackaryH8**

### CODE REVIEW

**Comment by pixlcrashr** [comment]
First of all, thank you for your contribution.

Nonetheless, I have to ask: Why you want the logo to be modified? - Or: what did you exactly change? Please explain.

Also note, that you did not modify all logos but one. For the sake of completeness please edit all logos.

I may note that, if you want to, I can give you the .psd file s.t. you can modify the logo without any visual artifacts.

**Review by pixlcrashr — CHANGES_REQUESTED** [review]
See the comment.

**Comment by ZackaryH8** [comment]
The current colour on the repo is outdated because alt:V updated their logo, I'd like to update all of the sizes but do not have photoshop so I'm unable to

**Comment by pixlcrashr** [comment]
> The current colour on the repo is outdated because alt:V updated their logo, I'd like to update all of the sizes but do not have photoshop so I'm unable to

What sizes exactly, except the V-icon?

**Comment by pixlcrashr** [comment]
Btw. Can't you open .PSD files using GIMP?

**Comment by ZackaryH8** [comment]
All other logo sizes updated :)

**Comment by pixlcrashr** [comment]
Looks good to me.

**Review by pixlcrashr — APPROVED** [review]

**Pull request merged**
